const
  TELEGRAM_TOKEN = 'YOUR TELEGRAM BOT TOKEN',
  WEBAPP_URL = 'YOUR GOOGLE WEBAPP URL',
  USER_TABLE = 'NAME OF SHEET WITH USERS',
  TIMEZONE_SHEET = 'NAME OF SHEET WITH Timezones',
  TZ_TOKEN = 'TIMEZONE DB TOKEN'